### ISSUE TITLE
Create Icon

### ISSUE THREAD

**Issue by gargvarun250** [shantanu109/CSC510_Group25_Project1#8]
@Sahil-Nande Can you please include this part into the logo.
https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.shutterstock.com%2Fsearch%2F86%2Blogo&psig=AOvVaw0cEHRBTNa9NF1GfUQAZ9jy&ust=1638736151434000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCOCQ04T-yvQCFQAAAAAdAAAAABAD

**Comment by Sahil-Nande** [comment]
On it!

**Comment by Sahil-Nande** [comment]
Created the logo for 86 No More. Please check it once.
